// Detailed, conversion-focused service pages, each routed at /services/[slug].
// The /services hub and the sitemap read from here. First-person Joe voice,
// no em/en dashes (client rule). Pricing facts only: free estimate, quote
// before work, no hidden fees, custom builds from $350 + parts, warranty.
import { SITE } from './site'

export const SERVICE_PAGES = [
  {
    slug: 'computer-repair',
    name: 'Computer & Laptop Repair',
    tag: 'Repair',
    metaTitle: 'Computer & Laptop Repair in Central Florida',
    metaDescription: "Slow, broken, or dead laptop or desktop? I fix Windows PCs and Macs in Kissimmee, Orlando, and St. Cloud. Free diagnostic, honest advice, warranty on parts and labor.",
    h1: 'Computer and Laptop Repair in Kissimmee and Central Florida',
    intro: "If your laptop or desktop is slow, will not turn on, or has a cracked screen, I can tell you what is wrong and what it costs before any work starts. I am Joe Witter, and I have repaired Windows PCs and Macs across Central Florida since 2019. The diagnostic and estimate are free, so you find out where you stand at no cost.",
    overview: "Computer repair means finding the real cause of the problem and fixing it, not guessing. I test the machine, explain what I find in plain language, and quote a price before I touch anything. I work on laptops and desktops, both Windows and Mac, on-site, remotely, or by drop-off, whichever is easiest for you.",
    included: [
      'Full diagnostic to find the actual cause, not just the symptom',
      'Fixing slow performance, freezing, blue screens, and boot failures',
      'Cracked or broken laptop screen replacement',
      'Liquid spill cleanup, overheating fixes, and fan and thermal cleaning',
      'Hard drive and SSD replacement, RAM upgrades, and battery and charging port repair',
      'Failed Windows update repair and full Windows reinstall when needed',
      'New computer setup with your files moved over from the old machine',
    ],
    notIncluded: [
      'Server setup and ongoing business networks, which fall under my business IT service',
      'Whole-home Wi-Fi and network wiring, which I handle as a separate networking job',
      'Data recovery from a physically failed drive, which is its own specialized service',
    ],
    bestFor: [
      'A laptop or desktop that has gotten slow and frustrating to use',
      'A computer that will not power on or stops at a black or blue screen',
      'A cracked laptop screen or a keyboard or port damaged by a drop or spill',
      'An older machine you are deciding whether to repair or replace',
      'Anyone who wants a new computer set up with files moved from the old one',
      'Mac and Windows users who want one honest local technician for both',
    ],
    outcomes: [
      'A computer that boots and runs at a normal speed again',
      'A working screen, keyboard, battery, or charging port',
      'Your photos, documents, and programs back in place and usable',
      'A clear answer on whether the machine is worth fixing or replacing',
      'No more random shutdowns from overheating or failing parts',
      'A repaired machine backed by a warranty on the parts and labor',
    ],
    process: [
      { h: 'Tell me what is wrong', p: `Call or text ${SITE.phone}, or email ${SITE.email}, and describe the problem. I will tell you whether on-site, remote, or drop-off makes the most sense.` },
      { h: 'Free diagnostic and estimate', p: 'I test the machine to find the real cause, then give you a clear price and honest advice on repair versus replacement. There is no charge and no obligation for this.' },
      { h: 'You decide, then I fix it', p: 'Nothing happens until you approve the quoted price. If you go ahead, I do the repair, often the same day when scheduling and parts allow.' },
      { h: 'Test, return, and back it up', p: 'I confirm everything works, return your computer with your files in place, and stand behind the parts and labor with a warranty.' },
    ],
    guarantees: [
      'Free diagnostic and estimate, with no obligation to move forward',
      'You get a firm price before any work begins, and you only pay if you go ahead',
      'No hidden fees: the price I quote is the price you pay',
      'Warranty on parts and labor, with screen replacements covered',
      'Payment by Cash, Zelle, CashApp, or Check',
    ],
    pricing: "The diagnostic and estimate are always free, with no obligation. After I find the problem, I quote a firm price before any work begins, so you decide with the full cost in front of you. There are no hidden fees, and you only pay if you choose to go ahead. The repair is backed by a warranty on parts and labor, and screen replacements are covered. I take Cash, Zelle, CashApp, and Check.",
    faq: [
      { q: 'How much will my repair cost?', a: "I cannot guess a fair price until I know the real problem, so the diagnostic and estimate are free. Once I find the cause, I give you a firm price before any work begins, with no hidden fees, and you only pay if you decide to go ahead." },
      { q: 'How long does a repair take?', a: 'Many repairs are done the same day when scheduling and parts allow. Jobs that need a part I have to order take longer, and I will tell you the timeline when I give you the estimate.' },
      { q: 'Will my files and data be safe?', a: "Keeping your files in place is part of the job, and on a new computer setup I move them over from the old machine. For anything important, I still recommend a backup first, and I am happy to walk you through one before I start." },
      { q: 'What if my computer cannot be fixed?', a: "If it is not worth repairing, I will tell you straight and explain why, rather than charging you for work that will not last. The diagnostic is still free, and I can help you choose and set up a replacement if you want." },
      { q: 'Do you work on both Mac and PC?', a: 'Yes. I repair both Windows PCs and Macs, laptops and desktops, so you can bring me either one.' },
      { q: 'Should I repair my computer or replace it?', a: "It depends on the age of the machine and what is wrong with it. I will give you my honest read during the free diagnostic. My tip on weighing repair versus replacement covers how I think about it." },
      { q: 'Where do you work, and do I have to come to you?', a: "I serve Kissimmee, Orlando, St. Cloud, Celebration, Davenport, Poinciana, Hunter's Creek, Lake Buena Vista, and the area near Disney. I can work on-site, remotely, or by drop-off, whichever suits you." },
      { q: 'What is the next step?', a: `Call or text me at ${SITE.phone}, or email ${SITE.email}. Describe what is going on, and I will set up your free diagnostic.` },
    ],
    related: [
      { href: '/services/data-recovery', label: 'Data Recovery' },
      { href: '/services/virus-malware-removal', label: 'Virus and Malware Removal' },
      { href: '/services/custom-pc-builds', label: 'Custom PC Builds' },
      { href: '/tech-tips/repair-vs-replace', label: 'Repair or Replace: How to Decide' },
      { href: '/contact', label: 'Contact Joe' },
    ],
  },
  {
    slug: 'virus-malware-removal',
    name: 'Virus & Malware Removal',
    tag: 'Security',
    metaTitle: 'Virus & Malware Removal in Central Florida',
    metaDescription: 'Slow, pop-up ridden, or hijacked computer? I remove viruses, spyware, ransomware, and browser redirects across Central Florida, then harden it. Free estimate first.',
    h1: 'Virus & Malware Removal in Kissimmee and Central Florida',
    intro: "If your computer is crawling, flooded with pop-ups, or redirecting your browser somewhere you never asked to go, I can get it clean and running like it should. This is for home users and small businesses around Kissimmee and Central Florida who want the problem fixed right, not patched over. A clean machine protects your accounts, your photos, and your time.",
    overview: "Virus and malware removal means finding and pulling out the harmful software hiding on your computer: viruses, spyware, adware, ransomware, browser redirects, and the pop-ups they push. I scan the machine with trusted tools, remove what does not belong, check the spots malware likes to hide, then update and harden the system so the same thing is less likely to come back. I work on both Mac and Windows.",
    included: [
      'A full scan of the system for viruses, spyware, adware, and other malware',
      'Removal of browser redirects, hijacked search settings, and constant pop-ups',
      'Cleanup of the fake full-screen "your computer is infected" warnings and the programs behind them',
      'A check of startup items and browser extensions for anything that does not belong',
      'Updates to the operating system and security software so known holes are closed',
      'Basic hardening so the machine is less likely to get reinfected',
      'A plain-language explanation of what I found and how to avoid it next time',
    ],
    notIncluded: [
      'Recovering files that ransomware or a virus has already encrypted or deleted: that is a separate data recovery job, and I will tell you honestly what is possible',
      'New hardware or parts if a component has actually failed: I quote those separately before ordering anything',
      'Ongoing managed security plans: this is a one-time cleanup, though I am glad to advise on staying protected',
      'Removing legal software you simply no longer want: I can do it, but that is general cleanup, not malware removal',
    ],
    bestFor: [
      'Home users whose computer suddenly got slow, loud, or covered in pop-ups',
      'Anyone seeing a full-screen "your computer is infected, call this number" warning',
      'People whose browser keeps redirecting to sites they never typed in',
      'Folks worried they clicked a bad link or attachment and want the machine checked',
      'Small businesses around Kissimmee that need a work computer cleaned and back in service',
      'Mac and Windows owners who want a real cleanup, not just a quick scan',
    ],
    outcomes: [
      'Pop-ups, fake warnings, and browser redirects gone',
      'A computer that boots and runs at a normal speed again',
      'Hijacked search engines and homepages set back to what you chose',
      'Spyware and adware that was watching or slowing you down removed',
      'Known security holes closed so the same infection is less likely to return',
      'A clear picture of how it got in and what to watch for going forward',
    ],
    process: [
      { h: 'Tell me what is happening', p: `Call or text me at ${SITE.phone}, or email ${SITE.email}, and describe what you are seeing: pop-ups, a slow machine, a warning on the screen. We figure out whether on-site, remote, or drop-off fits best.` },
      { h: 'Free diagnostic and estimate', p: 'I look at the machine, confirm what is going on, and give you a clear price before any work begins. The diagnostic and estimate are free, with no obligation to go ahead.' },
      { h: 'Cleanup and hardening', p: "Once you approve, I remove the malware, undo the redirects and pop-ups, and check the usual hiding spots. Then I update and harden the system. If anything looks risky to your files, I stop and tell you first." },
      { h: 'Check, explain, and hand back', p: 'I confirm the machine is running clean and at normal speed, walk you through what I found, and share a few simple steps to stay safer. Then you have your computer back.' },
    ],
    guarantees: [
      'Free diagnostic and estimate, with no obligation',
      'You get a price quote before any work begins, with no hidden fees',
      'You only pay if you decide to go ahead',
      'Warranty on parts and labor for any work I do',
      'If your files are ever at risk during the cleanup, I stop and tell you first',
    ],
    pricing: "The diagnostic and estimate are always free, with no obligation. I look at the machine, tell you what is wrong, and quote a clear price before any work begins, so you know the cost up front with no hidden fees. You only pay if you decide to go ahead. Any parts or labor I do come with a warranty. I take Cash, Zelle, CashApp, or Check.",
    faq: [
      { q: 'How much does virus and malware removal cost?', a: "The diagnostic and estimate are free, with no obligation. After I see what is going on, I quote a flat, clear price before I start any work, so there are no surprises and no hidden fees. You only pay if you decide to go ahead." },
      { q: 'How long does it take?', a: 'Most cleanups are done the same day or the next, depending on how deep the infection is and how the machine is running. Same-day is possible when scheduling and any needed parts allow. I will give you a realistic time frame once I have looked at it.' },
      { q: 'Will my files and data be safe?', a: "In most cleanups your files stay right where they are: photos, documents, and the rest. Removing malware does not normally mean wiping the machine. If I ever see that something puts your files at risk, I stop and tell you first before doing anything." },
      { q: 'What if the computer cannot be fixed or the files are already gone?', a: "I will tell you straight. If malware has already encrypted or deleted files, that becomes a data recovery question, and I will be honest about what is and is not possible. You still pay nothing for the free diagnostic if you choose not to move forward." },
      { q: 'Do you work on both Mac and PC?', a: 'Yes. I clean malware off both Mac and Windows computers, laptops and desktops alike. The tools differ a little, but the goal is the same: a clean, safe machine that runs the way it should.' },
      { q: 'I got a full-screen pop-up saying my computer is infected and to call a number. Is that real?', a: "Almost always, no. A real warning will not lock your screen and demand you call a phone number. That is a tech-support scam designed to scare you into calling and handing over money or remote access. Do not call the number. Shut the page down if you can and reach out to me, and I will check the machine for real." },
      { q: 'Someone called saying they were tech support and found a virus. Should I trust them?', a: "No. Legitimate companies do not cold-call you about a virus on your computer. These callers want remote access or payment. Do not give them access or any card numbers. If you are worried something is wrong, I will look at the machine and tell you what is actually there." },
      { q: 'What is the next step?', a: `Call or text me at ${SITE.phone}, or email ${SITE.email}. Tell me what you are seeing and we will set up on-site, remote, or drop-off service. The diagnostic and estimate are free, so the first step costs you nothing.` },
    ],
    related: [
      { href: '/tech-tips/tech-support-scam-warning-signs', label: 'Tech Support Scam Warning Signs' },
      { href: '/services/data-recovery', label: 'Data Recovery' },
      { href: '/services/computer-repair', label: 'Computer Repair' },
      { href: '/tech-tips/protect-home-network', label: 'How to Protect Your Home Network' },
      { href: '/contact', label: 'Contact Joe' },
    ],
  },
  {
    slug: 'data-recovery',
    name: 'Data Recovery',
    tag: 'Data',
    metaTitle: 'Data Recovery in Kissimmee and Orlando',
    metaDescription: 'Lost files or photos from a failing or deleted drive? I recover data for Mac and Windows across Central Florida. Free diagnostic, no fee if I cannot recover it.',
    h1: 'Data Recovery in Central Florida',
    intro: "Losing the only copy of your photos, documents, or work files is a sick feeling, and I get it. I am Joe Witter, and I have spent 13 plus years working in IT. When a drive fails, stops showing up, or files disappear, I try to get them back. Photos and irreplaceable files come first. The diagnostic and estimate are free, and you only pay if I actually recover your data.",
    overview: "Data loss happens in a lot of ways: a hard drive that clicks or will not spin up, an SSD that suddenly is not recognized, a folder you deleted by mistake, a drive that reads as raw or corrupted, or a ransomware attack that locked your files. I work through these calmly and honestly. First I look at the drive and tell you what I see and what it will cost, before any work starts. If I can recover your files, I get them off safely and copy them somewhere reliable. After that, I help you set up a backup so one failed drive never puts you in this spot again. I work on both Mac and Windows drives, on-site, remotely, or by drop-off here in Central Florida.",
    included: [
      'Free diagnostic to check the drive and tell you honestly what can be recovered and what it will cost',
      'Recovery from failing or dead hard drives, including drives that are slow, clicking, or not spinning up',
      'Recovery from SSDs that are not recognized, corrupted, or showing errors',
      'Recovery of accidentally deleted files, folders, and photos when the data has not been overwritten',
      'Repair of corrupted, raw, or unreadable file systems on Mac and Windows drives',
      'Help getting files back after a ransomware attack when recovery is possible',
      'Setting up a reliable backup afterward so a single drive failure does not cost you your files again',
    ],
    notIncluded: [
      'Clean-room repair of severe physical or mechanical damage, like platter or motor damage, which needs a specialist lab. I will tell you up front and can point you to one.',
      'Recovery of files that have already been overwritten by new data, which cannot be brought back',
      'Guaranteed results on every drive. Some drives are too far gone, and I will be honest about that before you spend anything',
    ],
    bestFor: [
      'Anyone with photos or irreplaceable files trapped on a drive that stopped working',
      'A hard drive that clicks, freezes, or no longer shows up on your computer',
      'An SSD or USB drive that suddenly is not recognized or reads as corrupted',
      'Files or folders deleted by accident that you need back',
      'A computer hit by ransomware that locked your documents and photos',
      'Anyone who recovered their files once and wants a backup set up so it does not happen again',
    ],
    outcomes: [
      'Your photos, documents, and important files copied safely off the failing drive',
      'A clear, honest answer about what can be recovered before you spend a dollar',
      'Recovered files handed back to you on a drive or location you can rely on',
      'A working backup in place so the next drive failure is an inconvenience, not a disaster',
      'A clear understanding of exactly what happened and what your options are',
    ],
    process: [
      { h: 'Tell me what happened', p: `Call or text me at ${SITE.phone} and describe the drive and how you lost access. I will let you know whether to bring it in, mail it, or set up an on-site or remote look.` },
      { h: 'Free diagnostic and honest estimate', p: 'I examine the drive and tell you what I can recover and what it will cost, before any work begins. If it needs a clean-room lab for physical damage, I tell you that up front and can point you to one.' },
      { h: 'Recover your files', p: 'With your go-ahead, I work to pull your photos and files off safely, putting irreplaceable items first. I do not charge for an attempt that does not succeed.' },
      { h: 'Hand back and verify', p: 'I copy your recovered files to a reliable drive or location and confirm with you that the important ones opened and are all there.' },
      { h: 'Set up a backup', p: 'I help you put a simple, reliable backup in place so a single failed drive never costs you your files again. I will walk you through keeping it going.' },
    ],
    guarantees: [
      'Free diagnostic and estimate, with no obligation to go ahead',
      'I quote the price before any work begins, with no hidden fees',
      'You only pay if you decide to go ahead, and I do not charge for a recovery attempt that does not succeed',
      'If your drive needs a specialist clean-room lab, I tell you honestly and up front and can point you to one',
      'Warranty on parts and labor for any repair work involved',
    ],
    pricing: "The diagnostic and estimate are always free, with no obligation. After I look at your drive, I quote a flat price before any work begins, so there are no hidden fees and no surprises. You only pay if you decide to go ahead, and I do not charge for a recovery attempt that does not succeed. If your drive turns out to need a specialist clean-room lab, I tell you honestly before you spend anything. I take Cash, Zelle, CashApp, and Check.",
    faq: [
      { q: 'How much does data recovery cost?', a: 'The diagnostic and estimate are free, with no obligation. Once I have looked at the drive, I quote you a flat price before any work begins, so you know the cost up front with no hidden fees. You only pay if you decide to go ahead, and I do not charge for a recovery attempt that does not succeed.' },
      { q: 'How long does data recovery take?', a: 'It depends on the drive and how much data is involved. Some recoveries are done the same day when scheduling allows, and others take longer, especially with larger or badly damaged drives. After the free diagnostic I will give you a realistic time frame along with the price.' },
      { q: 'Will my files and personal information be safe?', a: 'Yes. I handle your photos, documents, and personal information carefully and privately, and I put irreplaceable files first. Your recovered data is copied to a reliable drive or location and handed back to you, not shared with anyone.' },
      { q: 'What if my files cannot be recovered?', a: 'I will be honest with you up front about the odds before you spend anything. If a recovery attempt does not succeed, I do not charge you for it. If the drive has severe physical damage that needs a clean-room lab, I tell you that and can point you to a specialist.' },
      { q: 'Do you work on both Mac and PC?', a: 'Yes. I recover data from both Mac and Windows drives, as well as external hard drives, SSDs, and USB drives. Let me know what kind of device it is when you reach out and I will tell you the best way to get it to me.' },
      { q: 'Can you recover files after I accidentally deleted them?', a: 'Often, yes, as long as the data has not been overwritten by new files. The sooner you stop using the drive after a deletion, the better the chances. Bring it to me or reach out before saving anything else to that drive.' },
      { q: 'Can you help after a ransomware attack?', a: 'Sometimes. Depending on how the attack locked your files, I can recover what is recoverable and help you get back to a clean, safe setup. I will look at it during the free diagnostic and tell you honestly what your options are.' },
      { q: 'What is the next step?', a: `Call or text me at ${SITE.phone} or email ${SITE.email} and tell me what happened with the drive. I will set up a free diagnostic, and if you want, help you put a backup in place afterward so this does not happen again.` },
    ],
    related: [
      { href: '/tech-tips/how-to-back-up-your-data', label: 'How to Back Up Your Data' },
      { href: '/services/computer-repair', label: 'Computer Repair' },
      { href: '/services/virus-malware-removal', label: 'Virus and Malware Removal' },
      { href: '/services/custom-pc-builds', label: 'Custom PC Builds' },
      { href: '/contact', label: 'Contact Joe' },
    ],
  },
  {
    slug: 'wifi-networking',
    name: 'Wi-Fi & Home Networking',
    tag: 'Networking',
    metaTitle: 'Wi-Fi & Home Networking in Kissimmee & Orlando',
    metaDescription: 'I fix Wi-Fi dead zones and set up routers, mesh, and small office networks across Kissimmee, Orlando, and Central Florida. Free diagnostic, honest pricing.',
    h1: 'Wi-Fi and Home Networking in Central Florida',
    intro: "If your Wi-Fi drops in the back bedroom, slows down when everyone is home, or just will not reach the garage, I can fix it. I am Joe Witter, and I have spent 13 years working in IT. I come to your home or small office, find out why the signal is failing, and set things up so the connection holds in the rooms you actually use. Before I leave, I test the spots that were giving you trouble.",
    overview: "Most Wi-Fi problems come down to a few things: a router in the wrong place, hardware that is too old or too cheap for the space, walls and distance that block the signal, or too many devices fighting for one connection. I look at your actual home or office, not a guess. I check where your router sits, how far the signal has to travel, and where the dead zones are. Then I recommend what will fix it, whether that means moving the router, adding a mesh system for whole-home coverage, running a cable to a far room, or setting up a proper small office network. I quote the price before any work begins, so you know what you are paying for.",
    included: [
      'Testing your current Wi-Fi to find dead zones, weak spots, and where the signal drops',
      'Setting up and placing routers and mesh systems for coverage across the whole home or office',
      'Running and tidying network cabling so wires are routed cleanly and out of the way',
      'Configuring a separate guest network and a network for smart-home devices',
      'Setting up small office networks with switches and access points for more devices and wired connections',
      'Securing the network with proper passwords and settings so it is not left wide open',
      'Testing coverage and speed in the actual problem spots before I leave',
    ],
    notIncluded: [
      'Monthly internet service itself, which comes from your provider, not from me',
      'Running new cable inside finished walls that requires opening and patching drywall',
      "Repairs to the provider line coming into the building, which is the provider's responsibility",
    ],
    bestFor: [
      'Homes with dead zones where Wi-Fi will not reach a bedroom, garage, patio, or upstairs',
      'Families whose connection slows down or drops when several people are streaming or on calls',
      'People who bought a new router or mesh system and want it set up and placed right',
      'Smart homes with cameras, thermostats, and speakers that need a steady, separate network',
      'Small offices that need switches, access points, and wired connections for more devices',
      'Anyone moving into a new home in Central Florida who wants the network done right from the start',
    ],
    outcomes: [
      'Wi-Fi that reaches the rooms you use, including the far ones that used to drop',
      'A connection that holds steady when several people and devices are online at once',
      'Smart-home devices on their own network so they stay connected and out of the way',
      'A guest network that keeps visitors off your main devices',
      'Cabling that is run cleanly instead of left loose across the floor',
      'A small office network that can handle the devices and connections your work depends on',
    ],
    process: [
      { h: 'We talk about what is happening', p: 'Call or text me and tell me where the Wi-Fi fails and what you are trying to cover. I come out, or for some setups I can start remotely, and look at the actual space.' },
      { h: 'I find the real problem', p: 'I test the signal around your home or office, check where the router sits, and pin down the dead zones and weak spots. The diagnostic and estimate are free, with no obligation.' },
      { h: 'I quote it, then do the work', p: 'I tell you what will fix it and what it costs before I start. Once you say go, I place or set up the router or mesh, run any cabling, and configure your guest and smart-device networks.' },
      { h: 'I test the spots that were failing', p: 'Before I leave, I check coverage and speed in the rooms and corners that were giving you trouble, so we both know it is actually fixed.' },
    ],
    guarantees: [
      'Free diagnostic and estimate, with no obligation',
      'I quote the price before any work begins, and there are no hidden fees',
      'You only pay if you decide to go ahead',
      'Warranty on parts and labor',
      'Coverage tested in the actual problem spots before I leave',
    ],
    pricing: "The diagnostic and estimate are free, with no obligation. I quote the price before any work begins, so you always know what you are paying for before I start, and there are no hidden fees. You only pay if you decide to go ahead. The cost depends on what your space needs, whether that is moving and configuring your current router, adding a mesh system, running cabling, or setting up an office network with switches and access points. Hardware like a mesh system or switch is quoted separately so you can see what the parts cost. Parts and labor are covered by warranty. I take Cash, Zelle, CashApp, and Check.",
    faq: [
      { q: 'How much will it cost to fix my Wi-Fi?', a: 'It depends on what your space needs, so I do not guess at it over the phone. The diagnostic and estimate are free, with no obligation. I come out, find the cause, and quote the full price before I start any work. There are no hidden fees, and you only pay if you decide to go ahead.' },
      { q: 'How long does it take?', a: 'Many Wi-Fi fixes and router or mesh setups are done in a single visit. Larger jobs, like running cabling or wiring a small office network, can take longer. I can often do same-day work when scheduling and parts allow, and I tell you the timing when I give you the quote.' },
      { q: 'Do I need to buy new equipment?', a: 'Not always. Sometimes the fix is moving and reconfiguring the router you already have. If your hardware really is the problem, I tell you that and quote the part separately, so you can see what it costs before you decide. I will not push gear you do not need.' },
      { q: 'Will it reach my whole house or office?', a: 'That is the goal, and it is why I test the actual problem spots before I leave. For larger or multi-floor spaces, a mesh system or added access points can cover the areas a single router cannot. I plan the setup around the rooms and corners you need covered.' },
      { q: 'Can you set up a separate network for guests and smart-home devices?', a: 'Yes. I can set up a guest network that keeps visitors off your main devices, and a separate network for smart-home gear like cameras, thermostats, and speakers so they stay steady and out of the way of your main computers.' },
      { q: 'How do I know I can trust you with my network?', a: `I am Joe Witter, one technician, and I have been doing this in Central Florida since 2019, with 13 years in IT and a ${SITE.rating.value} rating from ${SITE.rating.count} reviews on Google. I hold CompTIA A+ and Network+ and Microsoft MCSE and MCSA certifications, with Security+ and CISSP in progress. I tell you what I am doing and why, and I quote the price before I start.` },
      { q: 'Do you work on small office networks, not just homes?', a: 'Yes. I set up small office networks with switches and access points so you can connect more devices, add wired connections where you need them, and keep guest and internal traffic separate. I cover both homes and small offices across Central Florida.' },
      { q: 'What is the next step?', a: `Call or text me at ${SITE.phone}, or email ${SITE.email}. Tell me where your Wi-Fi is failing and what you need covered, and we will set up a time for the free diagnostic and estimate.` },
    ],
    related: [
      { href: '/tech-tips/fix-wifi-dead-zones', label: 'Tech Tip: Fix Wi-Fi Dead Zones' },
      { href: '/tech-tips/protect-home-network', label: 'Tech Tip: Protect Your Home Network' },
      { href: '/services/smart-home-security', label: 'Smart Home & Security' },
      { href: '/services/business-it', label: 'Business IT Support' },
      { href: '/services/computer-repair', label: 'Computer Repair' },
    ],
  },
  {
    slug: 'business-it',
    name: 'Small Business IT Support',
    tag: 'Business',
    metaTitle: 'Small Business IT Support in Central Florida',
    metaDescription: 'Local IT support for small businesses and offices in Kissimmee, Orlando, and near Disney. You get Joe, a certified technician, not a call center. Free assessment.',
    h1: 'Small Business IT Support in Central Florida',
    intro: "I keep the technology behind your small business working so you can run it. I am Joe Witter, and I have spent 13 plus years in IT, with CompTIA and Microsoft certifications behind the work. When you call or text, you reach me directly, not a ticket queue or an offshore call center. I handle your network, your email, your security, and your backups, and I explain what I am doing in plain language. Whether you need a one-time project or steady monthly support, you get one local contact who knows your setup.",
    overview: "Small offices in Central Florida do not need a big managed services contract to get reliable IT. They need someone who shows up, knows the systems, and answers the phone. I work with businesses in Kissimmee, Orlando, St. Cloud, Celebration, Davenport, Poinciana, Hunter's Creek, Lake Buena Vista, and near Disney, on-site, remotely, or by drop-off. I set up and manage networks and Wi-Fi, Microsoft 365 and business email, security and data backup, new-employee and device setup, printers, and shared files. You can bring me in for a single project or keep me on a monthly support plan with priority response. Either way, the work is quoted before it starts, and you get a real person who already knows how your office runs.",
    included: [
      'Business network and Wi-Fi setup, troubleshooting, and management for your office',
      'Microsoft 365 and business email setup, administration, and ongoing account management',
      'Security and data backup so your files and accounts are protected and recoverable',
      'New-employee onboarding: computer, accounts, email, and access set up and ready to use',
      'Printer, scanner, and shared-file setup so everyone in the office can work together',
      'Device setup and configuration for new and replacement computers',
      'Monthly support plans with priority response and one local point of contact',
    ],
    notIncluded: [
      'Custom software development or building applications from scratch',
      'Large enterprise data center or server-farm projects beyond a small office',
      'Phone-system and VoIP carrier contracts, which I can advise on but do not sell',
    ],
    bestFor: [
      'Small offices and professional practices with a handful of computers',
      'Home-based businesses and solo owners who need one reliable tech contact',
      'Retail shops and local storefronts that rely on a point-of-sale and Wi-Fi',
      'Real estate, insurance, and accounting offices running Microsoft 365',
      'Clinics, salons, and service businesses that need secure client records',
      'Growing teams adding employees and devices who need setup done right',
    ],
    outcomes: [
      'Your network and Wi-Fi stay reliable, so work does not stop for technical problems',
      'Your email and Microsoft 365 accounts are set up correctly and managed for you',
      'Your business data is backed up and recoverable if hardware fails or files are lost',
      'New employees start with a working computer, email, and access on day one',
      'You have one local contact who knows your setup and answers when you call',
      'You know what IT will cost before any work begins, with no surprises',
    ],
    process: [
      { h: 'Free assessment', p: 'We talk about how your office runs, what is working, and what is not. I look at your network, computers, email, and backups. There is no charge for this and no obligation.' },
      { h: 'Quote before any work', p: 'I give you a clear price for the work, quoted before I start. You decide whether to go ahead. You only pay if you do, and there are no hidden fees.' },
      { h: 'Setup and fixes', p: 'I do the work on-site, remotely, or by drop-off, whichever fits your office. Same-day is possible when scheduling and parts allow. I keep you posted as I go.' },
      { h: 'Handoff in plain language', p: 'When the work is done, I show you what changed and how to use it. No jargon. You know what I did and why, and how to reach me if you need me.' },
      { h: 'Ongoing support', p: 'If you want steady help, a monthly support plan gives you priority response and one local contact. You keep working, and I keep an eye on your technology.' },
    ],
    guarantees: [
      'Free assessment and estimate, with no obligation to move forward',
      'Every price is quoted before any work begins, with no hidden fees',
      'You only pay if you decide to go ahead',
      'Warranty on parts and labor, so the work is backed up',
      'Payment by Cash, Zelle, CashApp, or Check, whatever is easiest for you',
    ],
    pricing: "The first step is a free assessment of your setup, with no obligation. Once I see what your office needs, I quote a clear price before any work begins, so you know the cost up front and there are no hidden fees. You only pay if you decide to go ahead. For ongoing help, monthly support plans are available with priority response and one local point of contact. Tell me how your office runs and I will recommend the right fit and put a number to it before you commit.",
    faq: [
      { q: 'How much does small business IT support cost?', a: 'It depends on what your office needs, so I start with a free assessment and no obligation. After that I quote a clear price before any work begins, with no hidden fees, and you only pay if you go ahead. For ongoing help, monthly support plans are available, and I will give you the number once I understand your setup.' },
      { q: 'Do you support just one person, or do I need a whole team?', a: 'Both. I work with solo owners and home-based businesses as well as small offices with several employees. You do not need a minimum number of computers or a big contract. If you are one person who just needs reliable IT, that is exactly the kind of client I help.' },
      { q: 'How fast can you respond if something breaks?', a: 'When you call or text, you reach me directly, so there is no queue to wait through. Same-day service is possible when scheduling and parts allow. On a monthly support plan you get priority response, which means your issues move to the front of the line.' },
      { q: 'Can you keep my business secure and back up our data?', a: 'Yes. I set up security and data backup so your accounts and files are protected and recoverable if hardware fails or files are lost. I hold CompTIA Security certifications and have Security+ and CISSP in progress, and I keep the protection practical for a small office.' },
      { q: 'I already have an IT person or company. Can you take over?', a: 'Yes. I can review your current setup during the free assessment, document how things are configured, and take over network, email, and backup management without disrupting your work. I will tell you plainly what I find and what, if anything, should change.' },
      { q: 'Do you come to my office, or is everything remote?', a: 'Whatever fits. I work on-site at offices across Central Florida, remotely when that is faster, or by drop-off. Many issues I can handle remotely the same day. For setup and network work, I often come to you so everything is right in your space.' },
      { q: 'What is included in a monthly support plan?', a: 'A monthly plan gives you priority response and one local contact, me, instead of a call center. I keep an eye on your technology, help with the day-to-day issues, and stay familiar with how your office runs so problems get solved faster. Tell me your setup and I will recommend a fit.' },
      { q: 'What is the first step to get started?', a: `Call or text me at ${SITE.phone}, or email ${SITE.email}. We will set up a free assessment of your office with no obligation. I will look at what you have, tell you what I would do, and quote it before any work begins.` },
    ],
    related: [
      { href: '/tech-tips/microsoft-365-small-business', label: 'Microsoft 365 for Small Business' },
      { href: '/tech-tips/cybersecurity-for-small-business', label: 'Cybersecurity for Small Business' },
      { href: '/services/wifi-networking', label: 'Wi-Fi and Networking' },
      { href: '/services/data-recovery', label: 'Data Recovery' },
      { href: '/contact', label: 'Contact Joe' },
    ],
  },
  {
    slug: 'custom-pc-builds',
    name: 'Custom & Gaming PC Builds',
    tag: 'Builds',
    metaTitle: 'Custom & Gaming PC Builds in Central Florida',
    metaDescription: "I build custom desktops and gaming PCs spec'd to your budget and your actual use. Free estimate, parts and labor warranty, builds start at $350 plus parts.",
    h1: 'Custom and Gaming PC Builds in Central Florida',
    intro: "I am Joe Witter, and I build custom desktop computers for people in and around Kissimmee and Orlando. The goal is simple: the right machine for what you actually do, at a price that makes sense. I pick parts for your use case and your budget, put it together cleanly, set up Windows and the drivers, test it under load, and hand it over ready to use. If you want your old files moved over, I do that too. No upselling, no parts you do not need.",
    overview: "A good build starts with a conversation, not a parts list. I want to know what you plan to run, whether that is the latest games at high frame rates, video and photo editing, or a quiet machine for working from home. From there I source parts that fit the job and the number you have in mind, then assemble everything with proper cable management so the inside is neat and the airflow is good. After the operating system and drivers are installed, I stress test the system to make sure it holds up before it leaves my hands. You get a computer that is built for you, quoted up front, with a warranty on parts and labor. Builds start at $350 plus the cost of parts, and I quote the full price before I order anything.",
    included: [
      'Spec consultation: I learn what you need the machine to do and set a target budget before any parts are chosen.',
      'Parts sourcing: I select the CPU, GPU, memory, storage, motherboard, power supply, and case to fit your use and your budget, and I quote it all up front.',
      'Clean assembly: I build the system carefully and route the cables for a tidy interior and good airflow.',
      'Operating system and driver setup: I install Windows and the current drivers so the machine is ready to use out of the box.',
      'Stress testing: I run the system under load to confirm it is stable before you get it.',
      'Data and file transfer: if you want your files, photos, and documents moved from an old computer, I handle that.',
      'Up front quote: you see the full price, parts and labor, before I order a single component.',
    ],
    notIncluded: [
      "I do not sell prebuilt stock machines off a shelf. Every build is spec'd for the person who is going to use it.",
      'I do not push parts you do not need to hit a higher price. The build matches the use, not a sales target.',
      'I do not quote a number and then surprise you with hidden fees. The price you approve is the price you pay, plus any parts changes you ask for.',
    ],
    bestFor: [
      'Gamers who want solid frame rates at the resolution they actually play at, without overpaying for parts they will not use.',
      'Video and photo editors and other creators who need a machine that handles large files and long renders.',
      'People working from home who want a quiet, dependable computer that just works every day.',
      'Students who need a capable machine that will last through their program without breaking the budget.',
      'Anyone who wants the right machine for the job, not an overpriced one or an underpowered one.',
    ],
    outcomes: [
      'A computer matched to what you do, so you are not paying for power you will never touch or fighting a machine that cannot keep up.',
      'A clean, well organized build with good cable management and airflow, which helps the system run cooler and stay reliable.',
      'A system that is already tested under load, so problems show up on my bench, not on your desk.',
      'Windows and drivers set up and your old files moved over, so you can sit down and get to work right away.',
      'A clear, up front price with a warranty on parts and labor, so there are no surprises after the fact.',
    ],
    process: [
      { h: 'We talk about what you need', p: `Free consultation, no obligation. Tell me what you want to run and roughly what you want to spend. I work on-site, remotely, or by phone and text at ${SITE.phone}, whatever is easiest for you.` },
      { h: 'I spec the build and quote it', p: 'I put together a parts list that fits your use and your budget, then give you the full price, parts and labor, before anything is ordered. You approve it first. For builds, a parts deposit may be discussed in advance.' },
      { h: 'I source and assemble', p: 'Once you approve, I order the parts and build the machine, routing cables cleanly for a tidy interior and good airflow.' },
      { h: 'I set up and stress test', p: 'I install Windows and the current drivers, then run the system under load to confirm it is stable before it goes anywhere.' },
      { h: 'You get it ready to go', p: 'I deliver the machine set up and ready to use, with your old files moved over if you wanted that. Same-day is possible when scheduling and parts allow.' },
    ],
    guarantees: [
      'Free consultation and estimate, with no obligation to move forward.',
      'I quote the full price before any parts are ordered, so you always approve the number first.',
      'No hidden fees. The price you approve is the price you pay.',
      'Warranty on parts and labor.',
      'Payment by Cash, Zelle, CashApp, or Check, and for builds a parts deposit may be discussed in advance.',
    ],
    pricing: "Custom builds start at $350 plus the cost of parts, and that part cost depends on the components your build calls for. I quote the full price, parts and labor, before I order anything, so you approve the number first and there are no hidden fees. For builds, a parts deposit may be discussed in advance so I can order your components. Payment is by Cash, Zelle, CashApp, or Check. The consultation and estimate are free, with no obligation.",
    faq: [
      { q: 'Is a custom build cheaper than buying a prebuilt computer?', a: 'It depends on what you need, but the real advantage is value. With a custom build, every dollar goes toward parts that fit how you use the machine, instead of paying for a configuration someone else decided on. I will tell you honestly what your build costs: builds start at $350 plus parts, quoted before I order anything, so you can compare for yourself.' },
      { q: 'How long does a build take?', a: 'Most of the timeline is sourcing the parts. Once I have everything in hand, assembly, setup, and stress testing usually move quickly. Same-day is possible when scheduling and parts allow. I give you a realistic timeframe when I quote the build.' },
      { q: 'Can I bring my own parts?', a: 'Yes. If you already have parts you want to use, I will work with them and fill in whatever else the build needs. I will also tell you honestly if a part you have is a good fit for the rest of the system or if it will hold you back.' },
      { q: 'Will my new computer have a warranty?', a: 'Yes. Your build comes with a warranty on parts and labor. If something I installed gives you trouble, reach out and I will take care of it.' },
      { q: 'Can you transfer my old files to the new machine?', a: 'Yes. If you want your files, photos, and documents moved from your old computer, I handle that as part of the build, so the new machine is ready to use when you get it.' },
      { q: 'How do I know I am getting the right parts and not being oversold?', a: 'I spec the build around what you actually do and the budget you set, not around hitting a higher price. You see the full parts list and the price before I order anything, so nothing is a mystery. If a cheaper part does the job, that is what I recommend.' },
      { q: 'Do you only build gaming PCs?', a: 'No. I build gaming rigs, but I also build editing and creative workstations and dependable machines for home office and school work. Tell me what you need it to do and I will spec it for that.' },
      { q: 'What is the next step?', a: `Call or text me at ${SITE.phone} or email ${SITE.email} for a free consultation and estimate, no obligation. Tell me what you want the machine to do and roughly what you want to spend, and I will put together a build and a price for you.` },
    ],
    related: [
      { href: '/services/computer-repair', label: 'Computer Repair' },
      { href: '/tech-tips/ssd-upgrade-signs', label: 'Signs You Need an SSD Upgrade' },
      { href: '/services/data-recovery', label: 'Data Recovery' },
      { href: '/service-areas', label: 'Service Areas' },
      { href: '/contact', label: 'Contact Joe' },
    ],
  },
  {
    slug: 'smart-home-security',
    name: 'Smart Home & Security Cameras',
    tag: 'Smart Home',
    metaTitle: 'Smart Home & Security Cameras in Central FL',
    metaDescription: 'I install security cameras, video doorbells, smart locks, and thermostats across Central Florida, on a secure network and connected to your phone. Free assessment.',
    h1: 'Smart Home and Security Camera Setup in Central Florida',
    intro: "I am Joe Witter, and I set up smart home devices and security cameras for homes and small businesses around Kissimmee, Orlando, and near Disney. The goal is simple: cameras, doorbells, locks, and thermostats that actually work, that you can check from your phone, and that are placed on a separate, secure network so they cannot be used as a way into your personal computers and files. Before I leave, everything is tested and you know how to use it.",
    overview: "A smart home is only useful when the pieces talk to each other and you can trust them. I handle the whole setup: mounting and configuring cameras and video doorbells, installing smart locks and thermostats, connecting a hub if your devices need one, and getting every device showing up correctly in the app on your phone. I also put these devices on their own network, kept apart from the laptops and phones that hold your personal information, so a single weak gadget does not put the rest of your home at risk. I have been working in IT for 13 years, I hold CompTIA A+ and Network+ along with Microsoft MCSE and MCSA, and I am working on Security+ and CISSP. I work on-site, and same-day service is possible when scheduling and parts allow.",
    included: [
      'Security cameras: placement, mounting, and configuration so you see the views that matter',
      'Video doorbells set up with motion alerts and clear notifications to your phone',
      'Smart locks installed and paired so you can lock, unlock, and share access from the app',
      'Smart thermostats installed and connected to your schedule and phone',
      'Smart-home hubs set up so your devices connect and work together reliably',
      'App setup on your phone, with each device named and tested while I am there',
      'Placing devices on a secure, separate network so they cannot reach your personal computers and files',
    ],
    notIncluded: [
      'I do not provide ongoing monitoring service contracts or monthly monitoring',
      'I do not run new electrical wiring or do structural work',
      'I do not sell alarm subscriptions or lock you into a recurring plan',
    ],
    bestFor: [
      'Homeowners who want cameras and smart devices set up correctly the first time',
      'Vacation-rental and short-term-rental owners near Disney who need guest Wi-Fi, smart locks, and cameras',
      'Busy families who want to check the door and the house from their phones',
      'Small businesses that want cameras and a smart front door on a secure network',
      'People replacing a do-it-yourself setup that never worked the way it should',
    ],
    outcomes: [
      'Cameras and doorbells you can check from your phone, at home or away',
      'Smart locks you can open and share without handing out physical keys',
      'Devices on their own network, kept apart from the computers that hold your files',
      'A thermostat and hub that follow your schedule instead of fighting you',
      'A setup that is tested and working before I leave, with no loose ends',
      'A clear walkthrough so you know how to use what you paid for',
    ],
    process: [
      { h: 'Free assessment', p: 'I look at your home or business, your Wi-Fi, and the devices you have or are thinking about. I tell you what will work and what I would do, then give you a price before any work begins.' },
      { h: 'Install and configure', p: 'I mount and set up the cameras, doorbells, locks, thermostats, and hub. Each device is configured properly, not just powered on and left.' },
      { h: 'Secure network setup', p: 'I place your smart devices on a separate, secure network so a weak gadget cannot be used to reach your personal computers and files. Vacation rentals also get clean, separate guest Wi-Fi.' },
      { h: 'Connect to your phone', p: 'I get every device into the app on your phone, named clearly, with alerts set the way you want them.' },
      { h: 'Test and walk through', p: 'I test everything together and show you how to use it, so it all works before I leave and you are not left guessing.' },
    ],
    guarantees: [
      'Free assessment and estimate, with no obligation',
      'You get a price before any work begins, and you only pay if you go ahead',
      'No hidden fees',
      'Warranty on parts and labor',
      'Honest advice: if a simpler or cheaper option fits you better, I will tell you',
    ],
    pricing: "It starts with a free assessment and estimate, with no obligation. I look at your space, your Wi-Fi, and your devices, then quote a price before any work begins. There are no hidden fees, and you only pay if you decide to go ahead. Parts and labor are covered by a warranty. I take Cash, Zelle, CashApp, and Check. If a simpler or less expensive approach will get you what you need, I will say so.",
    faq: [
      { q: 'How much does a smart home or camera setup cost?', a: 'It depends on how many devices you have and how your home is laid out, so I do not guess. I start with a free assessment, then give you a price before any work begins. There are no hidden fees, and you only pay if you go ahead.' },
      { q: 'Which camera or smart-home system should I buy?', a: 'Tell me what you want to do and I will help you choose. I am not tied to one brand, so I can recommend devices that fit your home, your phone, and your budget. If you already bought something, I will work with what you have when it makes sense.' },
      { q: 'Do I need a monthly subscription?', a: 'Not from me. I do not sell monitoring contracts or recurring plans. Some camera or lock brands offer their own optional cloud plans, and I will tell you plainly what each one does so you can decide. Plenty of setups work well without one.' },
      { q: 'Is a smart home secure? I worry about cameras getting hacked.', a: 'That is a fair concern, and it is why I put your smart devices on a separate, secure network, kept apart from the computers and phones that hold your personal files. That way a single weak device cannot be used as a path to the rest of your home. I also set strong sign-ins on the apps and devices.' },
      { q: 'Will this work with my Wi-Fi?', a: 'Usually, yes. During the assessment I check your Wi-Fi and how far the signal reaches. If a camera or doorbell sits in a weak spot, I will tell you before we start and explain what it would take to fix the coverage so your devices stay connected.' },
      { q: 'I own a vacation rental near Disney. Can you help with that?', a: 'Yes. Short-term rentals are a good fit: smart locks so you can give guests a code instead of a key, cameras for the exterior and entry points, and separate guest Wi-Fi that keeps guests off the network running your devices. I set it up so it is easy to manage between stays.' },
      { q: 'Do you install the devices, or just set up the apps?', a: 'Both. I mount and install the cameras, doorbells, locks, thermostats, and hub, configure each one, put them on a secure network, and connect them to your phone. I do not run new electrical wiring, but the device setup itself is handled start to finish.' },
      { q: 'What is the next step?', a: `Call or text me at ${SITE.phone}, or email ${SITE.email}. Tell me what you are trying to set up and where you are, and I will schedule a free assessment. Same-day service is possible when scheduling and parts allow.` },
    ],
    related: [
      { href: '/services/wifi-networking', label: 'Wi-Fi and Home Networking' },
      { href: '/tech-tips/smart-home-setup-guide', label: 'Smart Home Setup Guide' },
      { href: '/tech-tips/protect-home-network', label: 'How to Protect Your Home Network' },
      { href: '/services/business-it', label: 'Business IT Support' },
      { href: '/contact', label: 'Contact Joe' },
    ],
  },
]

export function getServicePage(slug) {
  return SERVICE_PAGES.find(s => s.slug === slug)
}
